# -*- coding: utf-8 -*-
"""Level2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGRCEX5pAXyWs6KGO4L3JuTrGtYX3MO6

# 최솟값 만들기

- 길이가 같은 배열 A,B 두개가 있음
- A, B에서 각각 한개의 숫자를 뽑아 두 수를 곱합니다.
- 이러한 과정을 배열의 길이만큼 반복, 두 수를고반 값을 누적하여 더함
- 누적된 값이 최소가 되도록 만드는 것이 목표
- 단, 각 배열에서 k번째 숫자를 뽑았다면 다음에 k번째 숫자는 못뽑음
"""

A = [1, 4, 2]
B = [5, 4, 4]

A =[1,2]
B = [3, 4]

def solution(A,B):
    A = sorted(A, reverse =True)
    B = sorted(B)
    answer = 0
    for i in range(len(A)):
      answer += A[i] *B[i]


    return answer