# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15bwn8mOno3yuUvKNyBSv6dLQEX956EE7

# [1차] 비밀지도
"""

arr1 = [9, 20, 28, 18, 11]
arr2 = [30, 1, 21, 17, 28]

def solution(n, arr1, arr2):
    line = 0
    map =[]
    n=''
    for i,j in zip(arr1,arr2) :
      a = list(format(i, 'b').zfill(5))
      b = list(format(j, 'b').zfill(5))
      for k in range(5):
        if b[k] == '0' and a[k] == '0':
          n += " "
        else:
          n += '#'
      line +=1
      map.append(n)
      n =''
    return map

map

def solution(n, arr1, arr2):
    answer = []
    for i,j in zip(arr1,arr2):
        a12 = str(bin(i|j)[2:])
        a12=a12.rjust(n,'0')
        a12=a12.replace('1','#')
        a12=a12.replace('0',' ')
        answer.append(a12)
    return answer