# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15bwn8mOno3yuUvKNyBSv6dLQEX956EE7
"""

from datetime import datetime
def solution(a, b):
    date =['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']
    return date[datetime(2016, a, b).weekday()]


solution(5, 24)