# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tdmS2sBvr2XtpjIwArKUHWt71Prqw6_a
"""

from collections import deque

# 현수막 크기
M, N = map(int, input().split())

# 현수막 정보 
map_ =  [list(map(int, input().split())) for _ in range(M)]

# 이동 거리
d = [
     (1, 0), 
     (-1, 0), 
     (0, 1), 
     (0, -1),
     (1, -1),
     (1, 1),
     (-1, 1),
     (-1, -1)
]

result = 0


def bfs(x, y):
  q = deque()
  q.append((x, y))

  while q:
    x,y = q.popleft()
    for dx, dy in d:
      nx, ny = x+dx, y +dy
      
      # 이동거리가 현수막 범위 안에 있고 1면
      if 0<=nx<M and 0 <= ny < N and map_[nx][ny] == 1:

        # 0으로 바꿈
        map_[nx][ny] =0
        q.append((nx, ny))



for i in range(M):
  for j in range(N):
    if map_[i][j]==1:
      bfs(i, j)
      result +=1

print(result)